project:
  type: book
  output-dir: "book"
biblio-title: References
bibliography: cites.bib
biblio-style: mla
link-citations: true
nocite: '@*'
csl: modern-language-association.csl
pdf-cover: "images/cover.png"
pdf-logo: "images/cover-logo.png"
pdf-cover-author-color: "61, 60, 59"
pdf-cover-font-color: "255, 255, 255"
pdf-logo-size: 5cm
theme-color: "248, 149, 34"
trademark: Eclipse Quneiform
publisher: Eclipse Foundation AISBL
publisher-logo: "images/publisher-logo.png"
publisher-cities:
  - Brussels
  - Ottawa
  - Darmstadt
book:
  title: "Eclipse Quneiform 2026"
  subtitle: "User Manual"
  description: Internationalization & localization analysis system
  author: Blake Madden
  date: today
  date-format: "YYYY"
  output-file: "quneiform"
  language: en
  chapters:
    - index.qmd
    - building.qmd
    - part: "i18n & l10n Issues"
      chapters:
      - issues/i18n-issues.qmd
    - part: "Command-line Utility"
      chapters:
      - command-line/options.qmd
      - command-line/examples.qmd
      - command-line/reviewing-output.qmd
    - part: "User Interface"
      chapters:
      - gui/new-project.qmd
      - gui/reviewing-output.qmd
      - gui/editing.qmd
      - gui/tools.qmd
      - gui/options.qmd
    - part: "Additional Features"
      chapters:
      - suppression.qmd
  appendices:
    - acknowledgements.qmd
format:
  pdf:
    documentclass: LegrandOrangeBook
    template: latex/default.tex
    include-in-header: latex/preamble.tex
    latex-engine: xelatex
    keep-tex: true
    citation-package: biblatex
    cite-method: biblatex
    lot: false
    code-block-bg: false
    CJKmainfont: NotoSerifJP
    CJKoptions:
      - Path=./fonts/NotoSerifJP/
      - Extension=.ttf
      - UprightFont=*-VariableFontwght
    linkcolor: black
    citecolor: black
